# Generated by Django 3.2.4 on 2022-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity_hi',
            fields=[
                ('entityId', models.BigIntegerField(db_column='entityId', editable=False, primary_key=True, serialize=False)),
                ('entityName', models.CharField(db_column='entityName', max_length=1000)),
            ],
            options={
                'db_table': 'Entity_hi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='entitySurfaceNames_hi',
            fields=[
                ('SNo', models.BigIntegerField(db_column='SNo', primary_key=True, serialize=False)),
                ('frequency', models.BigIntegerField(blank=True, null=True)),
                ('label', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entitySurfaceNames_hi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='surfaceNames_hi',
            fields=[
                ('surfaceNamesId', models.BigIntegerField(db_column='surfaceNamesId', primary_key=True, serialize=False)),
                ('surfaceName', models.CharField(db_column='surfaceName', max_length=750)),
            ],
            options={
                'db_table': 'surfaceNames_hi',
                'managed': False,
            },
        ),
    ]
