# Generated by Django 2.2 on 2022-05-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageDuplicates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention_hi',
            fields=[
                ('instanceid', models.BigIntegerField(db_column='instanceId', primary_key=True, serialize=False)),
                ('sentence', models.CharField(blank=True, max_length=450, null=True)),
                ('link', models.CharField(blank=True, max_length=105, null=True)),
                ('editDistance', models.BigIntegerField(blank=True, db_column='editDistance', null=True)),
                ('isCorrectSubstring', models.BigIntegerField(blank=True, db_column='isCorrectSubString', null=True)),
                ('isCorrectSuperstring', models.BigIntegerField(blank=True, db_column='isCorrectSuperString', null=True)),
            ],
            options={
                'db_table': 'Mention_hi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mention2_hi',
            fields=[
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('dest', models.CharField(blank=True, max_length=100, null=True)),
                ('SN', models.CharField(blank=True, db_column='SN', max_length=145, null=True)),
                ('context', models.CharField(blank=True, max_length=250, null=True)),
                ('instanceId', models.OneToOneField(db_column='instanceId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='imageDuplicates.Mention_hi')),
            ],
            options={
                'db_table': 'Mention2_hi',
                'managed': False,
            },
        ),
    ]
