# Generated by Django 2.2 on 2022-05-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageDuplicates', '0002_mention2_hi_mention_hi'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entitysurfacenames_hi',
            table='entitySurfaceNames_hi2',
        ),
    ]
